steps:
# Execute Build, Test and Package
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ["clean compile package test site", "-Dmaven.test.skip=true"]
# Create Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/config-ui', '.']
images: ['gcr.io/$PROJECT_ID/config-ui']