steps:
# Execute Compile and Package
- name: maven:3.8.1
  id: compile-code
  entrypoint: mvn
  args: ["compile","package", "-Dmaven.test.skip=true"]
# Create Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: create-docker-image
  args: ['build', '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}', '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID', '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA' , '.']
# Push Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: push-docker-image
  args: [ 'push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}']
# Update Compute Engine
- name: 'gcr.io/cloud-builders/gcloud'
  id: deploy-image
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh ${_GCE_NAME} --command='/bin/bash /opt/config-ui/docker-compose restart'
substitutions:
    _IMAGE_NAME: config-ui
    _GCE_NAME: instance-1
options:
   substitution_option: 'ALLOW_LOOSE'