name: trigger jenkins on close of PR
on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - feature*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger build
      uses: actions/cache@v1
      with:
        url: "http://35.223.181.63:8080/"
        user: "Phani Shankar Munukuta"
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        job: "githubWorkflow"
        run: mvn clean package com.google.cloud.tools:jib-maven-plugin:2.5.0:build -Dimage=registry.hub.docker.com/asyovan/global_configurations
